### ISSUE TITLE
"average" column

### ISSUE THREAD

**Issue by webzunft** [Halu95/easy-digital-report#2]
Add a column – where it makes sense – for the average revenue.
E.g., average revenue of sales by country.

**Comment by Halu95** [comment]
added in [ee03551](https://github.com/Halu95/easy-digital-report/commit/ee03551d871b96c9ff813d5b1005f20ad017f6fe).

**Comment by webzunft** [comment]
@Halu95 please without taxes :)

**Comment by Halu95** [comment]
Aye: [2ff1bec](https://github.com/Halu95/easy-digital-report/commit/2ff1bec73af1ebf7d6ef79f405e1a2d371d84f37)
