### ISSUE TITLE
Tax rates not fetched properly

### ISSUE THREAD

**Issue by Halu95** [Halu95/easy-digital-report#3]
There are cases wrong tax rates are fetched from edd.

The relevant line in the export file can be seen here:
https://github.com/Halu95/easy-digital-report/blob/master/includes/edr_export.php#L30

**Comment by Halu95** [comment]
@webzunft any idea what could go wrong here?

**Comment by webzunft** [comment]
@Halu95 sent you a reply in our Trello issue with a suggestion.

**Comment by Halu95** [comment]
solved by using the original edd method instead of the method of the vat expansion
